name: Build i2b2 data warehouse Docker Images

## Don't build images on main, we should only be pushing tested, successfully building, commits to main
on:
  push:
    branches-ignore:
      - "main"

env:
  REGISTRY: ghcr.io

jobs:
  web:
    runs-on: ubuntu-latest
    ## Only run job if commit message doesn't contain "WIP:" or "ci skip" is not triggered by dependabot
    if: |
      !startsWith(github.event.head_commit.message, 'WIP:') &&
      !contains(github.event.head_commit.message, 'ci skip') &&
      !contains(github.ref, 'dependabot')
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image for ${{ github.job }}
        uses: docker/build-push-action@v6
        with:
          context: ./docker/${{ github.job }}
          file: ./docker/${{ github.job }}/Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}/i2b2-${{ github.job }}:build-latest
            ${{ env.REGISTRY }}/${{ github.repository }}/i2b2-${{ github.job }}:build-${{ github.run_number }}
            ${{ env.REGISTRY }}/${{ github.repository }}/i2b2-${{ github.job }}:sha-${{ github.sha }}
          push: true
  wildfly:
    runs-on: ubuntu-latest
    ## Only run job if commit message doesn't contain "WIP:" or "ci skip" is not triggered by dependabot
    if: |
      !startsWith(github.event.head_commit.message, 'WIP:') &&
      !contains(github.event.head_commit.message, 'ci skip') &&
      !contains(github.ref, 'dependabot')
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image for ${{ github.job }}
        uses: docker/build-push-action@v6
        with:
          context: ./docker/${{ github.job }}
          file: ./docker/${{ github.job }}/Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}/i2b2-${{ github.job }}:build-latest
            ${{ env.REGISTRY }}/${{ github.repository }}/i2b2-${{ github.job }}:build-${{ github.run_number }}
            ${{ env.REGISTRY }}/${{ github.repository }}/i2b2-${{ github.job }}:sha-${{ github.sha }}
          push: true
  database:
    runs-on: ubuntu-latest
    ## Only run job if commit message doesn't contain "WIP:" or "ci skip" is not triggered by dependabot
    if: |
      !startsWith(github.event.head_commit.message, 'WIP:') &&
      !contains(github.event.head_commit.message, 'ci skip') &&
      !contains(github.ref, 'dependabot')
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image for ${{ github.job }}
        uses: docker/build-push-action@v6
        with:
          context: ./docker/${{ github.job }}
          file: ./docker/${{ github.job }}/Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}/i2b2-${{ github.job }}:build-latest
            ${{ env.REGISTRY }}/${{ github.repository }}/i2b2-${{ github.job }}:build-${{ github.run_number }}
            ${{ env.REGISTRY }}/${{ github.repository }}/i2b2-${{ github.job }}:sha-${{ github.sha }}
          push: true
